#!/bin/bash

export SED_ARGS=${SED_ARGS:--i}

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

mkdir -p "$script_dir/dist/bin"

"$script_dir/replace" "$script_dir/master-scripts/learn-master" "$script_dir/replacements/common-replace" "$script_dir/replacements/learn-replace" "$script_dir/dist/bin/learn"
"$script_dir/replace" "$script_dir/master-scripts/check-master" "$script_dir/replacements/common-replace" "$script_dir/replacements/check-replace" "$script_dir/dist/bin/check"
"$script_dir/replace" "$script_dir/master-scripts/checkmain-master" "$script_dir/replacements/common-replace" "$script_dir/replacements/checkmain-replace" "$script_dir/dist/bin/checkmain"

