#!/bin/bash

# This file is part of the "learn-unix-scripts" project.
#
# The "learn-unix-scripts" project is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# The "learn-unix-scripts" project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with this project; if not, write to the
# Free Software Foundation, 59 Temple Place - Suite 330, Boston, MA, 02111-1307, USA.
#
# Copyright (C) 2021 Christopher Evans

# This verify script's purpose is to help in confirming that all features and dependencies that the scripts use are
# available.  This script should be run the same way students are expected to run these scripts (for example, if students
# are expected to run these scripts by using PuTTY to SSH into an on-campus server, this script should be run the same
# way).

# This script was developed in a 130x30 terminal.

parent_proc_name=`ps -p $PPID -o comm=`
echo "Checking that the parent process is bash."
if [[ ! "$parent_proc_name" =~ "bash" ]]; then
	echo "The parent process is $parent_proc_name.  An interactive bash shell was expected."
	echo "The scripts in this project are written in bash and require the user to use the bash shell."
	echo "But they're open source, so feel free to use the lesson text and write your own."
	exit 1
fi

echo "Checking for bash version 4 or later."
if [[ "${BASH_VERSINFO:-0}" < "4" ]]; then
	if [ -f /usr/local/bin/bash ]; then
		homebrew=$(/usr/local/bin/bash -c 'echo ${BASH_VERSINFO[0]}')
		#echo "/bin/bash too old, checking Homebrew version:  $homebrew"
		if [[ "$homebrew" < "4" ]]; then
			echo "Associative array support, added in Bash 4.0, is required.  Homebrew bash not found either."
			echo "If you have a Mac, install Homebrew, then install bash."
			exit 2
		#else
			#echo "Homebrew bash installed."
		fi
	else
		echo "Associative array support, added in Bash 4.0, is required."
		echo "If you have a Mac, install Homebrew, then install bash."
		exit 2
	fi 
fi 

echo "Checking stty arguments."
if stty --version 2>&1 | grep -q 'version'; then
    # BusyBox and other streamlined systems don't support --version.
    stty_options='-a'
else
    if stty --version 2>/dev/null | grep -q 'coreutils'; then
        stty_options='-a'
    else
        stty_options='everything'
    fi
fi

echo "Checking interrupt character."
stty ${stty_options} | grep -q "intr = ^C"
if [ $? -ne 0 ]; then
	echo "The interrupt character is not Ctrl+C or could not be parsed from the output of stty."
	echo "The exercises specifically say to use Ctrl+C, so if you can't change it, you"
	echo "will need to tell all students the correct interrupt character."
	exit 3
fi

if ! which tput > /dev/null; then
	echo "tput is not installed and is required.  It's part of ncurses."
	exit 4
fi

if ! which fmt > /dev/null; then
	echo "fmt is not installed and is required.  It's part of the coreutils package."
	exit 5
fi

if ! which man > /dev/null; then
	echo "man is not installed and is required."
	exit 6
fi

echo 
echo 
echo "Verify that some of the words in this sentence are red." | grep --color=always "some of the words"
echo "Verify that some of the words in $(tput setaf 196)this sentence are also$(tput sgr0) red."
echo
echo "If either of those doesn't have any red words, you may want to check your"
echo "terminal settings and/or your TERM environment variable."

