#!/usr/bin/env bash

# bobsleep - not nearly as long as the Odinsleep.
# Checks periodically if its parent has died, and if so, gives up.

SLEEP_TIME=10

# 60 * 10 = 600 seconds (10 minutes)
SLEEP_COUNT=60

CUR_COUNT=0

while (($CUR_COUNT < $SLEEP_COUNT));
do
	PARENT_PID=$(bash -c "ps -o ppid= $$ | tr -d '[:space:]'")

	if [ "$PARENT_PID" == "1" ]; then
		exit 0
	fi

	CUR_COUNT=`expr $CUR_COUNT + 1`
	sleep $SLEEP_TIME
done

