#!/usr/local/bin/bash

# bobtheundying:  A bash script that "resists" termination signals

set -o nounset

if [ "${1:-}" != "--yes-really" ]; then
	echo "Bob should only be awoken as part of the black stripe exercises,"
  echo "which will teach you how to get rid of him."
	echo "If you're ready, execute 'bobtheundying --yes-really &'."
	exit 1
fi

TAKE_THAT[0]="Better luck next time!"
TAKE_THAT[1]="You missed!  I could do this all day!"
TAKE_THAT[2]="You can't kill me in a way that matters!"
TAKE_THAT[3]="You can't kill me!  I will not die!"
TAKE_THAT[4]="You can't kill me!  I am invincible!"
TAKE_THAT[5]="You can't kill me!  I will rise again!"
TAKE_THAT[6]="You can't kill me, I'll make a copy of myself!"

you_cannot_kill_me() {
	size=${#TAKE_THAT[@]}
	index=$(($RANDOM % $size))
	echo "${TAKE_THAT[$index]}"
  if [ -n "$pid" ]; then
    kill $pid
  fi
}

# Trap SIGTERM and print a "take that".
trap you_cannot_kill_me SIGTERM

echo "I am Bob!  I live again!"

# A loop to keep the script running for 5 minutes
for i in {1..30}; do
  sleep 10 &
  pid=$!
  wait $pid
done

echo "Bob has died of old age."
